name: Deploy Workspace

# Trigger the workflow manually
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add any build steps if needed, e.g., npm install, Jekyll build, etc.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        _site: ./  # Use the root if all files should be deployed as-is
        